# https://pauledenburg.com/sonarqube-postgres-docker-compose/
# Start this stack with: docker-compose up -d 
# You can reach your SonarQube instance at http://localhost:9000
# Use the default credentials admin/admin to login.
version: "3"

services:
  sonarqube:
    image: sonarqube:6.7.1
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - $PWD/sonarqube_conf:/opt/sonarqube/conf
      - $PWD/sonarqube_data:/opt/sonarqube/data
      - $PWD/sonarqube_extensions:/opt/sonarqube/extensions
      - $PWD/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - $PWD/sonarqube_db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - $PWD/postgresql_data:/var/lib/postgresql/data
