# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app_development
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8051:80
    environment:
      - PMA_ARBITRARY=1